
services:
  postgres:
    image: docker.io/postgres:latest
    restart: unless-stopped
    shm_size: 128mb
    volumes:
     - ./postgresdata:/var/lib/postgresql/data

    # These will be used in homeserver.yaml later on
    environment:
     - PGDATA=/var/lib/postgresql/data/pgdata
     - POSTGRES_PASSWORD=STRONGPASSWORD

  synapse:
    image: localhost/matrixdotorg/synapse
    #image: ghcr.io/element-hq/synapse:latest
    restart: unless-stopped
    #environment:
    # - SYNAPSE_SERVER_NAME=synapse
    # - SYNAPSE_REPORT_STATS=yes

    volumes:
     - ./synapse:/data
    #ports:
    #  - "8008:8008"

  mas:
    image: ghcr.io/element-hq/matrix-authentication-service:latest
    restart: unless-stopped
    environment:
     - MAS_CONFIG=/data/config.yaml
    volumes:
     - ./mas:/data
    #ports:
    #  - "8081:8081"

  bridge:
    image: localhost/go-test-bridgev2:latest
    restart: unless-stopped
    volumes:
     - ./bridge:/data
  
  nginx:
    image: docker.io/nginx:latest

    volumes:
     - ./nginx/http/.well-known/matrix/:/usr/share/nginx/html/.well-known/matrix/
     - ./nginx/conf.d:/etc/nginx/conf.d/
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/keys/nginx.key:/etc/ssl/private/nginx.key
     - ./nginx/keys/nginx.crt:/etc/ssl/certs/nginx.crt
    ports:
      - "8008:8008"
      - "8080:8080"
      - "8443:8443"
      - "8448:8448"
